"use client";

import { useState } from "react";
import { Download, Printer, Copy, Check, FileText } from "lucide-react";
import Button from "@/components/ui/Button";

interface Stop {
  id: string;
  address: string;
  name: string;
  lat?: number;
  lng?: number;
}

interface RouteStats {
  distance: string;
  duration: string;
}

interface RouteExportProps {
  stops: Stop[];
  routeStats: RouteStats | null;
}

/**
 * Generates a Mapbox Static Images API URL showing the route.
 * Uses the public token — no secret needed for static maps.
 */
function getStaticMapUrl(stops: Stop[], width = 600, height = 400): string | null {
  const token = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  if (!token) return null;

  const geoStops = stops.filter((s) => s.lat && s.lng);
  if (geoStops.length === 0) return null;

  // Mapbox pin markers: pin-s-{label}+{color}({lng},{lat})
  const pins = geoStops
    .map((s, i) => `pin-l-${i + 1}+4A90D9(${s.lng},${s.lat})`)
    .join(",");

  // Auto-fit bounds
  return `https://api.mapbox.com/styles/v1/mapbox/dark-v11/static/${pins}/auto/${width}x${height}@2x?access_token=${token}&padding=60`;
}

/**
 * Build a plain-text route summary.
 */
function buildRouteText(stops: Stop[], stats: RouteStats | null): string {
  const lines = [
    "STAKD Route Plan",
    "═".repeat(40),
    "",
  ];

  if (stats) {
    lines.push(`Total: ${stats.distance} | ${stats.duration}`);
    lines.push(`Stops: ${stops.length}`);
    lines.push("");
  }

  stops.forEach((stop, i) => {
    lines.push(`${i + 1}. ${stop.name}`);
    lines.push(`   ${stop.address}`);
    lines.push("");
  });

  lines.push("─".repeat(40));
  lines.push("Generated by STAKD");

  return lines.join("\n");
}

export default function RouteExport({ stops, routeStats }: RouteExportProps) {
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  if (stops.length < 2) return null;

  const handleCopyList = async () => {
    const text = buildRouteText(stops, routeStats);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportImage = async () => {
    setExporting(true);
    try {
      const staticUrl = getStaticMapUrl(stops);
      const text = buildRouteText(stops, routeStats);

      // Create a canvas combining the static map + text overlay
      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");
      if (!ctx) return;

      const mapW = 1200;
      const mapH = 800;
      const listH = stops.length * 56 + 120; // estimate list height
      canvas.width = mapW;
      canvas.height = mapH + listH;

      // Background
      ctx.fillStyle = "#0D1117";
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Load and draw static map
      if (staticUrl) {
        const img = new Image();
        img.crossOrigin = "anonymous";
        await new Promise<void>((resolve) => {
          img.onload = () => {
            ctx.drawImage(img, 0, 0, mapW, mapH);
            resolve();
          };
          img.onerror = () => resolve(); // Continue without map on error
          img.src = staticUrl;
        });
      }

      // Title bar
      const titleY = mapH + 20;
      ctx.fillStyle = "#4A90D9";
      ctx.font = "bold 28px -apple-system, BlinkMacSystemFont, sans-serif";
      ctx.fillText("STAKD Route Plan", 30, titleY + 28);

      if (routeStats) {
        ctx.fillStyle = "#8B949E";
        ctx.font = "18px -apple-system, BlinkMacSystemFont, sans-serif";
        ctx.fillText(
          `${stops.length} stops · ${routeStats.distance} · ${routeStats.duration}`,
          30,
          titleY + 58
        );
      }

      // Stop list
      let y = titleY + 90;
      stops.forEach((stop, i) => {
        // Number circle
        ctx.beginPath();
        ctx.arc(45, y + 8, 14, 0, Math.PI * 2);
        ctx.fillStyle = "#4A90D9";
        ctx.fill();
        ctx.fillStyle = "#FFFFFF";
        ctx.font = "bold 14px -apple-system, BlinkMacSystemFont, sans-serif";
        ctx.textAlign = "center";
        ctx.fillText(`${i + 1}`, 45, y + 13);
        ctx.textAlign = "left";

        // Name + address
        ctx.fillStyle = "#E6EDF3";
        ctx.font = "bold 18px -apple-system, BlinkMacSystemFont, sans-serif";
        ctx.fillText(stop.name, 72, y + 6);

        ctx.fillStyle = "#8B949E";
        ctx.font = "14px -apple-system, BlinkMacSystemFont, sans-serif";
        ctx.fillText(stop.address, 72, y + 26);

        y += 52;
      });

      // Download
      const link = document.createElement("a");
      link.download = `stakd-route-${new Date().toISOString().slice(0, 10)}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setExporting(false);
    }
  };

  const handlePrint = () => {
    const text = buildRouteText(stops, routeStats);
    const staticUrl = getStaticMapUrl(stops);
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>STAKD Route Plan</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; padding: 24px; color: #1a1a1a; }
          h1 { font-size: 22px; margin-bottom: 4px; }
          .stats { color: #666; margin-bottom: 16px; font-size: 14px; }
          .map { width: 100%; max-height: 400px; object-fit: cover; border-radius: 8px; margin-bottom: 20px; }
          .stop { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 12px; }
          .num { width: 28px; height: 28px; border-radius: 50%; background: #4A90D9; color: white; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 13px; flex-shrink: 0; }
          .name { font-weight: 600; font-size: 15px; }
          .addr { color: #666; font-size: 13px; }
          .footer { margin-top: 24px; color: #999; font-size: 12px; border-top: 1px solid #eee; padding-top: 12px; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body>
        <h1>STAKD Route Plan</h1>
        ${routeStats ? `<p class="stats">${stops.length} stops · ${routeStats.distance} · ${routeStats.duration}</p>` : ""}
        ${staticUrl ? `<img class="map" src="${staticUrl}" alt="Route map" />` : ""}
        ${stops.map((s, i) => `
          <div class="stop">
            <div class="num">${i + 1}</div>
            <div>
              <div class="name">${s.name}</div>
              <div class="addr">${s.address}</div>
            </div>
          </div>
        `).join("")}
        <div class="footer">Generated by STAKD · ${new Date().toLocaleDateString()}</div>
        <script>window.onload = () => setTimeout(() => window.print(), 500);</script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="secondary"
        size="sm"
        onClick={handleExportImage}
        disabled={exporting}
      >
        <Download className="w-3.5 h-3.5" />
        {exporting ? "Exporting..." : "Export"}
      </Button>
      <Button variant="ghost" size="sm" onClick={handlePrint}>
        <Printer className="w-3.5 h-3.5" />
      </Button>
      <Button variant="ghost" size="sm" onClick={handleCopyList}>
        {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
      </Button>
    </div>
  );
}
