// This file will be auto-generated by: npm run db:types
// For now, we define the shape manually to unblock development.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          location: string | null;
          is_public: boolean;
          tier: "free" | "pro" | "elite";
          tier_expires_at: string | null;
          reputation_score: number;
          total_trades: number;
          successful_trades: number;
          trade_disputes: number;
          verified_seller: boolean;
          ai_grades_used_this_month: number;
          // Migration 013 columns
          status: "active" | "suspended" | "banned";
          suspended_until: string | null;
          suspension_reason: string | null;
          ban_reason: string | null;
          last_sign_in_at: string | null;
          flagged_count: number;
          // Migration 023: Stripe billing columns
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          // Migration 024: Email preferences
          email_preferences: {
            marketing: boolean;
            price_alerts: boolean;
            trade_updates: boolean;
            weekly_digest: boolean;
          };
          email_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          is_public?: boolean;
          tier?: "free" | "pro" | "elite";
          email_preferences?: {
            marketing: boolean;
            price_alerts: boolean;
            trade_updates: boolean;
            weekly_digest: boolean;
          };
          email_verified?: boolean;
        };
        Update: {
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          is_public?: boolean;
          tier?: "free" | "pro" | "elite";
          tier_expires_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          email_preferences?: {
            marketing: boolean;
            price_alerts: boolean;
            trade_updates: boolean;
            weekly_digest: boolean;
          };
          email_verified?: boolean;
        };
        Relationships: [];
      };
      collections: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          category: string;
          cover_image_url: string | null;
          is_public: boolean;
          item_count: number;
          total_value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          category: string;
          cover_image_url?: string | null;
          is_public?: boolean;
        };
        Update: {
          name?: string;
          description?: string | null;
          category?: string;
          cover_image_url?: string | null;
          is_public?: boolean;
        };
        Relationships: [];
      };
      items: {
        Row: {
          id: string;
          collection_id: string;
          user_id: string;
          title: string;
          description: string | null;
          category: string;
          condition: string;
          grade_value: string | null;
          grading_company: string | null;
          year: number | null;
          brand: string | null;
          tags: string[];
          estimated_value: number | null;
          purchase_price: number | null;
          purchase_date: string | null;
          image_urls: string[];
          enhanced_image_url: string | null;
          is_for_sale: boolean;
          is_for_trade: boolean;
          attributes: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          collection_id: string;
          user_id: string;
          title: string;
          description?: string | null;
          category: string;
          condition: string;
          grade_value?: string | null;
          grading_company?: string | null;
          year?: number | null;
          brand?: string | null;
          tags?: string[];
          estimated_value?: number | null;
          purchase_price?: number | null;
          purchase_date?: string | null;
          image_urls?: string[];
          is_for_sale?: boolean;
          is_for_trade?: boolean;
          attributes?: Record<string, unknown>;
        };
        Update: {
          title?: string;
          description?: string | null;
          category?: string;
          condition?: string;
          grade_value?: string | null;
          grading_company?: string | null;
          year?: number | null;
          brand?: string | null;
          tags?: string[];
          estimated_value?: number | null;
          purchase_price?: number | null;
          purchase_date?: string | null;
          image_urls?: string[];
          enhanced_image_url?: string | null;
          is_for_sale?: boolean;
          is_for_trade?: boolean;
          attributes?: Record<string, unknown>;
        };
        Relationships: [];
      };
      price_history: {
        Row: {
          id: string;
          item_id: string;
          price: number;
          source: string;
          sale_date: string | null;
          listing_url: string | null;
          fetched_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          price: number;
          source: string;
          sale_date?: string | null;
          listing_url?: string | null;
        };
        Update: {
          price?: number;
          source?: string;
          sale_date?: string | null;
          listing_url?: string | null;
        };
        Relationships: [];
      };
      restocks: {
        Row: {
          id: string;
          user_id: string;
          store_name: string;
          store_address: string | null;
          item_found: string;
          category: string | null;
          description: string | null;
          image_url: string | null;
          freshness_score: number | null;
          verified_count: number;
          reported_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          store_name: string;
          store_address?: string | null;
          item_found: string;
          category?: string | null;
          description?: string | null;
          image_url?: string | null;
        };
        Update: {
          store_name?: string;
          store_address?: string | null;
          item_found?: string;
          category?: string | null;
          description?: string | null;
          image_url?: string | null;
        };
        Relationships: [];
      };
      routes: {
        Row: {
          id: string;
          user_id: string;
          name: string | null;
          waypoints: Json;
          optimized_order: number[] | null;
          total_distance_meters: number | null;
          total_duration_seconds: number | null;
          route_geometry: Json | null;
          provider: string;
          is_saved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name?: string | null;
          waypoints?: Json;
          provider?: string;
          is_saved?: boolean;
        };
        Update: {
          name?: string | null;
          waypoints?: Json;
          optimized_order?: number[] | null;
          total_distance_meters?: number | null;
          total_duration_seconds?: number | null;
          route_geometry?: Json | null;
          is_saved?: boolean;
        };
        Relationships: [];
      };
      follows: {
        Row: {
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          follower_id: string;
          following_id: string;
        };
        Update: never;
        Relationships: [];
      };
      posts: {
        Row: {
          id: string;
          user_id: string;
          content: string | null;
          image_urls: string[];
          post_type: string;
          item_id: string | null;
          restock_id: string | null;
          like_count: number;
          comment_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          content?: string | null;
          image_urls?: string[];
          post_type?: string;
          item_id?: string | null;
          restock_id?: string | null;
        };
        Update: {
          content?: string | null;
          image_urls?: string[];
          post_type?: string;
        };
        Relationships: [];
      };
      likes: {
        Row: {
          user_id: string;
          post_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          post_id: string;
        };
        Update: never;
        Relationships: [];
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          content: string;
        };
        Update: {
          content?: string;
        };
        Relationships: [];
      };
      grading_analyses: {
        Row: {
          id: string;
          item_id: string | null;
          user_id: string | null;
          image_url: string;
          category: string | null;
          estimated_grade: number | null;
          confidence: number | null;
          subgrades: Json;
          defects: string[];
          recommendation: string | null;
          raw_analysis: string | null;
          metadata: Json;
          actual_grade: number | null;
          actual_grading_company: string | null;
          feedback_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id?: string | null;
          user_id?: string | null;
          image_url: string;
          category?: string | null;
          estimated_grade?: number | null;
          confidence?: number | null;
          subgrades?: Json;
          defects?: string[];
          recommendation?: string | null;
          raw_analysis?: string | null;
          metadata?: Json;
        };
        Update: {
          actual_grade?: number | null;
          actual_grading_company?: string | null;
          feedback_date?: string | null;
        };
        Relationships: [];
      };
      authentications: {
        Row: {
          id: string;
          item_id: string | null;
          submitted_by: string | null;
          image_urls: string[];
          category: string | null;
          status: string;
          ai_score: number | null;
          ai_analysis: string | null;
          ai_flags: string[];
          community_votes_authentic: number;
          community_votes_fake: number;
          community_confidence: number | null;
          final_verdict: string | null;
          final_confidence: number | null;
          reviewed_by: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_id?: string | null;
          submitted_by?: string | null;
          image_urls: string[];
          category?: string | null;
          ai_score?: number | null;
          ai_analysis?: string | null;
          ai_flags?: string[];
        };
        Update: {
          status?: string;
          community_votes_authentic?: number;
          community_votes_fake?: number;
          community_confidence?: number | null;
          final_verdict?: string | null;
          final_confidence?: number | null;
          reviewed_by?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          entity_id: string | null;
          entity_type: string | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          entity_id?: string | null;
          entity_type?: string | null;
        };
        Update: {
          read?: boolean;
        };
        Relationships: [];
      };
      translation_cache: {
        Row: {
          id: string;
          original_hash: string;
          original_text: string;
          translated_text: string;
          source_locale: string;
          target_locale: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          original_hash: string;
          original_text: string;
          translated_text: string;
          source_locale?: string;
          target_locale: string;
        };
        Update: never;
        Relationships: [];
      };
      trades: {
        Row: {
          id: string;
          initiator_id: string;
          receiver_id: string;
          status: "pending" | "accepted" | "declined" | "completed" | "disputed" | "cancelled";
          initiator_items: string[];
          receiver_items: string[];
          initiator_cash: number;
          receiver_cash: number;
          message: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          initiator_id: string;
          receiver_id: string;
          initiator_items?: string[];
          receiver_items?: string[];
          initiator_cash?: number;
          receiver_cash?: number;
          message?: string | null;
        };
        Update: {
          status?: "pending" | "accepted" | "declined" | "completed" | "disputed" | "cancelled";
          initiator_items?: string[];
          receiver_items?: string[];
          initiator_cash?: number;
          receiver_cash?: number;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      trade_feedback: {
        Row: {
          id: string;
          trade_id: string;
          reviewer_id: string;
          reviewed_id: string;
          rating: number;
          comment: string | null;
          tags: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          trade_id: string;
          reviewer_id: string;
          reviewed_id: string;
          rating: number;
          comment?: string | null;
          tags?: string[];
        };
        Update: never;
        Relationships: [];
      };
      // ── Migration 013: Admin, Security, CMS ──────────────────
      admin_roles: {
        Row: {
          id: string;
          user_id: string;
          role: "super_admin" | "admin" | "moderator" | "support";
          granted_by: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role: "super_admin" | "admin" | "moderator" | "support";
          granted_by?: string | null;
          expires_at?: string | null;
        };
        Update: {
          role?: "super_admin" | "admin" | "moderator" | "support";
          expires_at?: string | null;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_role: string | null;
          action: string;
          target_type: string | null;
          target_id: string | null;
          payload: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_role?: string | null;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
        };
        Update: never;
        Relationships: [];
      };
      reports: {
        Row: {
          id: string;
          reporter_id: string | null;
          target_type: "post" | "comment" | "restock" | "item" | "user" | "trade";
          target_id: string;
          reason: string;
          details: string | null;
          status: "open" | "reviewed" | "dismissed" | "actioned";
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reporter_id?: string | null;
          target_type: "post" | "comment" | "restock" | "item" | "user" | "trade";
          target_id: string;
          reason: string;
          details?: string | null;
        };
        Update: {
          status?: "open" | "reviewed" | "dismissed" | "actioned";
          reviewed_by?: string | null;
          reviewed_at?: string | null;
        };
        Relationships: [];
      };
      announcements: {
        Row: {
          id: string;
          title: string;
          body: string | null;
          type: "info" | "warning" | "maintenance" | "feature";
          cta_label: string | null;
          cta_url: string | null;
          is_active: boolean;
          show_from: string | null;
          show_until: string | null;
          target_tier: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          body?: string | null;
          type?: "info" | "warning" | "maintenance" | "feature";
          cta_label?: string | null;
          cta_url?: string | null;
          is_active?: boolean;
          show_from?: string | null;
          show_until?: string | null;
          target_tier?: string | null;
          created_by?: string | null;
        };
        Update: {
          title?: string;
          body?: string | null;
          type?: "info" | "warning" | "maintenance" | "feature";
          cta_label?: string | null;
          cta_url?: string | null;
          is_active?: boolean;
          show_from?: string | null;
          show_until?: string | null;
        };
        Relationships: [];
      };
      cms_pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          content: Json;
          meta_title: string | null;
          meta_description: string | null;
          is_published: boolean;
          published_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          content?: Json;
          meta_title?: string | null;
          meta_description?: string | null;
          is_published?: boolean;
          created_by?: string | null;
        };
        Update: {
          title?: string;
          content?: Json;
          meta_title?: string | null;
          meta_description?: string | null;
          is_published?: boolean;
          published_at?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      membership_plans: {
        Row: {
          id: string;
          name: string;
          slug: string;
          tagline: string | null;
          price_monthly: number;
          price_annual: number;
          color: string | null;
          features: Json;
          limits: Json;
          is_active: boolean;
          is_public: boolean;
          sort_order: number;
          stripe_price_id_monthly: string | null;
          stripe_price_id_annual: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          tagline?: string | null;
          price_monthly?: number;
          price_annual?: number;
          color?: string | null;
          features?: Json;
          limits?: Json;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_annual?: string | null;
        };
        Update: {
          name?: string;
          tagline?: string | null;
          price_monthly?: number;
          price_annual?: number;
          color?: string | null;
          features?: Json;
          limits?: Json;
          is_active?: boolean;
          is_public?: boolean;
          sort_order?: number;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_annual?: string | null;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          discount_type: "percent" | "fixed";
          discount_value: number;
          applies_to_plan: string | null;
          max_uses: number | null;
          used_count: number;
          valid_from: string | null;
          valid_until: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          discount_type: "percent" | "fixed";
          discount_value: number;
          applies_to_plan?: string | null;
          max_uses?: number | null;
          valid_from?: string | null;
          valid_until?: string | null;
          is_active?: boolean;
          created_by?: string | null;
        };
        Update: {
          description?: string | null;
          discount_type?: "percent" | "fixed";
          discount_value?: number;
          max_uses?: number | null;
          valid_until?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      system_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_by?: string | null;
        };
        Update: {
          value?: Json;
          description?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      price_source_configs: {
        Row: {
          id: string;
          source_name: string;
          display_name: string;
          is_enabled: boolean;
          priority: number;
          refresh_interval_hours: number;
          last_refresh_at: string | null;
          last_error: string | null;
          error_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source_name: string;
          display_name: string;
          is_enabled?: boolean;
          priority?: number;
          refresh_interval_hours?: number;
        };
        Update: {
          display_name?: string;
          is_enabled?: boolean;
          priority?: number;
          refresh_interval_hours?: number;
          last_refresh_at?: string | null;
          last_error?: string | null;
          error_count?: number;
        };
        Relationships: [];
      };
      rate_limit_events: {
        Row: {
          id: string;
          identifier: string;
          endpoint: string;
          event_count: number;
          window_start: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          identifier: string;
          endpoint: string;
          event_count?: number;
          window_start?: string;
        };
        Update: {
          event_count?: number;
        };
        Relationships: [];
      };
    };
    Views: Record<string, {
      Row: Record<string, unknown>;
      Relationships: never[];
    }>;
    Functions: Record<string, {
      Args: Record<string, unknown>;
      Returns: unknown;
    }>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, Record<string, unknown>>;
  };
}

// Convenience type aliases
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Collection = Database["public"]["Tables"]["collections"]["Row"];
export type Item = Database["public"]["Tables"]["items"]["Row"];
export type PriceHistory = Database["public"]["Tables"]["price_history"]["Row"];
export type Restock = Database["public"]["Tables"]["restocks"]["Row"];
export type Route = Database["public"]["Tables"]["routes"]["Row"];
export type Post = Database["public"]["Tables"]["posts"]["Row"];
export type Comment = Database["public"]["Tables"]["comments"]["Row"];
export type GradingAnalysis = Database["public"]["Tables"]["grading_analyses"]["Row"];
export type Authentication = Database["public"]["Tables"]["authentications"]["Row"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];
export type Trade = Database["public"]["Tables"]["trades"]["Row"];
export type TradeFeedback = Database["public"]["Tables"]["trade_feedback"]["Row"];
// Migration 013
export type AdminRole = Database["public"]["Tables"]["admin_roles"]["Row"];
export type AuditLog = Database["public"]["Tables"]["audit_logs"]["Row"];
export type Report = Database["public"]["Tables"]["reports"]["Row"];
export type Announcement = Database["public"]["Tables"]["announcements"]["Row"];
export type CmsPage = Database["public"]["Tables"]["cms_pages"]["Row"];
export type MembershipPlan = Database["public"]["Tables"]["membership_plans"]["Row"];
export type Coupon = Database["public"]["Tables"]["coupons"]["Row"];
export type SystemSetting = Database["public"]["Tables"]["system_settings"]["Row"];
export type PriceSourceConfig = Database["public"]["Tables"]["price_source_configs"]["Row"];
